### ISSUE TITLE
Trees, Grass etc. Texture

### ISSUE THREAD

**Issue by ClockTheSenior** [Igrium/mc-world-export#49]
When Imported into Blender, the trees, grass and other vegetation are black.
![image](https://user-images.githubusercontent.com/106481085/224491934-7f81b6da-e09f-42ca-a74e-2d2b79284855.png)

This is how fixed it (for the leaves) in Blender:
![image](https://user-images.githubusercontent.com/106481085/224492173-fe605e0a-b767-4f37-950b-60d6f0617591.png)

**Comment by ClockTheSenior** [comment]
Since the water and the trees have the same material, the water is now a swampy green color.

**Comment by Sam54123** [comment]
Weird, you shouldn't need to manually override the tint. Can you send the offending `.replay` file?

**Comment by Sam54123** [comment]
And maybe also the blend file?

**Comment by ClockTheSenior** [comment]
I will do that today.

**Comment by ClockTheSenior** [comment]
[gimmeurdiscord.zip](https://github.com/Sam54123/mc-world-export/files/10951844/gimmeurdiscord.zip)

**Comment by ClockTheSenior** [comment]
here is the blendfile:
https://drive.google.com/file/d/12iW5SqX4pXJSZw51-srQUGOPtNLlKBPR/view?usp=sharing
