### ISSUE TITLE
Problem with compatibility with Sodium on 1.19.4

### ISSUE THREAD

**Issue by RIPEXGAMES** [Igrium/mc-world-export#61]
![image](https://github.com/Sam54123/mc-world-export/assets/66251106/f80bdcd9-c017-4b23-bd95-767e88a0ad5b)

**Comment by ThatError404** [comment]
Hello!

Sodium is not compatible with Replay Exporter, but that issue is being worked on. For updates and additional help, join the (unofficial) discord server. https://discord.gg/yMJNM5bATg
