### ISSUE TITLE
Thanks for your previous help!

### ISSUE THREAD

**Issue by BaiGave** [Igrium/mc-world-export#62]
Thanks a lot for your help! Now my blender plug-in can directly import minecraft maps (some modules can also be used), of course there are some defects, such as the problem of cross-section face culling, the problem of coloring biomes, but I already have ideas to solve these, Thanks again for your help!
![1](https://github.com/Sam54123/mc-world-export/assets/107
![2](https://github.com/Sam54123/mc-world-export/assets/107305554/9fe4e6df-0b76-4d7d-9cf4-7b355e4cc7f7)
305554/605efa27-d862-4188-b8c4-480cffd5040c)

**Comment by BaiGave** [comment]
![1](https://github.com/Sam54123/mc-world-export/assets/107305554/64f52acb-174e-4d5d-9622-b6e3f9d393ff)

**Comment by Igrium** [comment]
You're welcome!
