### ISSUE TITLE
Error when trying to enable addon in Blender 4.0

### ISSUE THREAD

**Issue by Gimer-Studios** [Igrium/mc-world-export#74]
When trying to enable the addon in blender 4.0 this error message appears. Is there a fix for this? This is a fresh install of blender.

https://github.com/Igrium/mc-world-export/assets/152042973/268b0285-f728-4857-9716-75d17e2c06ef

**Comment by Siriusmart** [comment]
> When trying to enable the addon in blender 4.0 this error message appears. Is there a fix for this? This is a fresh install of blender.
> Recording.2024-02-02.184955.mp4

hi, i am also having the same issue after updating to 4.0, how did u fix it

**Comment by Gimer-Studios** [comment]
> > When trying to enable the addon in blender 4.0 this error message appears. Is there a fix for this? This is a fresh install of blender.
> > Recording.2024-02-02.184955.mp4
> 
> hi, i am also having the same issue after updating to 4.0, how did u fix it

Use blender 3.6 LTS. You can find it on the blender website or just download it from the MS Store.
