### ISSUE TITLE
Some mobs don't show up in replay file

### ISSUE THREAD

**Issue by ashraldrails** [Igrium/mc-world-export#76]
some mobs, such as wolves or rabbits, don't show up in the replay file in blender

**Comment by Igrium** [comment]
Due to a limitation with how the Minecraft rendering engine works, only some mobs are supported. If you know programming, you can help the project by [adding support for more mobs](https://github.com/Igrium/mc-world-export/blob/main/doc/entity_export_design_doc.md).
