### ISSUE TITLE
Crashed on startup

### ISSUE THREAD

**Issue by Tels123GG** [Igrium/mc-world-export#80]
https://paste.ee/p/81KVN

**Comment by Igrium** [comment]
Which jar did you download from Modrinth?

**Comment by Tels123GG** [comment]
https://pasteboard.co/WtFSXxynul3V.jpg I can't add an image via github,

**Comment by Igrium** [comment]
Make sure You're using the one that doesn't say sources

**Comment by Tels123GG** [comment]
Use what?

**Comment by Igrium** [comment]
Check the version of the mod you get from modrinth

**Comment by Tels123GG** [comment]
After downloading JDK 21 and the mod from modrinth (I downloaded from realises) it worked for me
